---

- hosts: all
  become: true
  tasks:

  - name: Install htop, neofetch, msr-tools on Debian family OS
    tags: ubuntu, install
    apt:
      name:
        - htop
        - neofetch
        - msr-tools
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Upgrde Debian family OS
    tags: ubuntu, upgrade
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Check if reboot required
    tags: ubuntu, reboot-chk
    ansible.builtin.stat:
      path: /var/run/reboot-required
      get_checksum: no
    register: reboot_required_file
    when: ansible_facts['os_family'] == "Debian"

  - name: Reboot the server if required
    tags: ubuntu, reboot
    ansible.builtin.reboot:
    when: reboot_required_file.stat.exists == true

  - name: Remove dependencies that are no longer required
    tags: ubuntu, dependencies-rm
    ansible.builtin.apt:
      autoremove: yes
    when: ansible_facts['os_family'] == "Debian"
